### ISSUE TITLE
tile shadow at the corners

### ISSUE THREAD

**Issue by arsdragonfly** [FluffyStuff/riichi-mahjong-tiles#2]
where's the svg file for the shadow at the upper left & lower right corners?

**Comment by FluffyStuff** [comment]
It's actually right there in the repo (Front.svg and Back.svg).
Apparently the highlight isn't being rendered correctly in Firefox and Chrome (or maybe the format I saved it in is out of date).
Either way, if you open those files in Inkscape then you will see the highlights correctly.

**Comment by arsdragonfly** [comment]
Is there a way to make it display correctly in browsers? I really want to serve the svg on a web page in my upcoming project (a notebook for what-to-discard problems).
